fix(android): fix concurrency issue in timeoutmap(#419)
capacitor-community/bluetooth-le pull request #560
Opened 2023-08-08 07:59 UTC by Andy3189

Hashmap is not thread safe, which will lead to errors as mentioned in the #419. We suggest a concurrent queue for storing and accessing the timeout handlers in a safe way.

2023-08-10 05:32 UTC, pwespi commented
Thank you for this PR.

2023-08-10 05:39 UTC, pwespi requested changes

2023-08-10 05:39 UTC, pwespi commented on android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt
> +class WriteTimeout(
Many calls have a timeout, not only write. Should we call this `TimeoutHandler`?

2023-08-10 05:39 UTC, pwespi commented on android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt
> +import android.annotation.SuppressLint
This import seems to be unused.

2023-08-11 08:25 UTC, Andy3189 commented
Changes as requested, ive also removed some debugging residuals

2023-08-11 08:45 UTC, td-tomasz-joniec commented
What is the benefit of using ConcurrentLinkedQueue over ConcurrentHashMap in this situation?

2023-08-11 10:48 UTC, td-tomasz-joniec commented
> > What is the benefit of using ConcurrentLinkedQueue over ConcurrentHashMap in this situation?
> 
> Its related to how the key for the hashmap is generated. If we have 2 requests with the same data following each other, additional handling would have to be introduced, because otherwise the second request will just replace the reference with a new timeout and we lose the reference of the first timeout handler again

Does this only happen when there is called BleClient.disableQueue() ?

2023-08-11 11:08 UTC, Andy3189 commented
> disableQueue

We dont use that function and ran into #419, so its possible that there may be collusions.

2023-08-13 18:16 UTC, pwespi commented on android/src/main/java/com/capacitorjs/community/plugins/bluetoothle/Device.kt
> +    this.removeIf { item ->
> Call requires API level 24 (current min is 22): java.util.concurrent.ConcurrentLinkedQueue#removeIf 

Unfortunately `removeIf` requires API level 24, while Capacitor 5 apps typically have minSdkVersion 22.

2023-08-14 08:17 UTC, Andy3189 commented
the removeIf function is just a wrapper for an iterator, so we will just use that

2023-08-14 18:46 UTC, pwespi approved these changes

2023-08-14 18:48 UTC, merged

2023-08-14 18:48 UTC, pwespi commented
Thank you!

@all-contributors please add @Andy3189 for code.